addSbtPlugin("de.knutwalker"    % "sbt-knutwalker" % "0.1.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-ghpages"    % "0.5.3")
addSbtPlugin("com.typesafe.sbt" % "sbt-site"       % "0.8.1")
addSbtPlugin("com.eed3si9n"     % "sbt-unidoc"     % "0.3.2")
addSbtPlugin("org.scoverage"    % "sbt-scoverage"  % "1.5.1")
